version: "3.9"

services:
  crud_postgres:
    image: postgres:15
    container_name: crud_postgres
    restart: always
    environment:
      POSTGRES_DB: crud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - crud-network

  backend:
    build: .
    container_name: task-movil-api
    depends_on:
      - crud_postgres
    ports:
      - "8081:8081"
    networks:
      - crud-network

networks:
  crud-network:
    driver: bridge

volumes:
  pgdata:


